require('angular');
window.moment = require('moment');
require('moment/min/locales.js');
require('angular-route');
require('angular-animate');
require('angular-sanitize');
require('angular-resource');
require('angular-touch');
require('angular-moment');
require('angular-deckgrid');
require('./services/app.js');